[features]
seeds = false
[programs.localnet]
ticketbox = "AzEd3mnzYBu5nP1rK2dxpDbwFqiPtvgvS3gWfQPbXxnV"
[programs.devnet]
ticketbox = "AzEd3mnzYBu5nP1rK2dxpDbwFqiPtvgvS3gWfQPbXxnV"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p tsconfig.json -t 1000000 tests/*.ts"